name: Build Wheel

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install UV
              run: curl -LsSf https://astral.sh/uv/install.sh | sh
            - name: Sync
              run: uv sync --extra cpu
            - name: Build
              run: uv build --wheel
