name: Build Wheel

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install UV
              run: curl -LsSf https://astral.sh/uv/install.sh | sh
            - name: Build
              run: uv build --wheel
    publish:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Publish wheel
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*.whl
