name: Tests

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - uses: astral-sh/setup-uv@v3
            - name: Install deps
              run: uv sync
            - name: Run tests
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  MISTTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
              run: uv run pytest -q
